// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5RsYrFVX9oFdkPZo5f1z9TCLf4iD4yC0',
    appId: '1:1003518765466:web:f509f79c825d0db95e3223',
    messagingSenderId: '1003518765466',
    projectId: 'loginfirebase-aabf3',
    authDomain: 'loginfirebase-aabf3.firebaseapp.com',
    storageBucket: 'loginfirebase-aabf3.firebasestorage.app',
    measurementId: 'G-CP7RPC1EPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8eOcJnzBxNilvnncdKpdoEA28_8wyoiQ',
    appId: '1:1003518765466:android:15402db8f472a30d5e3223',
    messagingSenderId: '1003518765466',
    projectId: 'loginfirebase-aabf3',
    storageBucket: 'loginfirebase-aabf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZxFRN4f6iuS5xWVe_mK8fpdNuUw7j0Y',
    appId: '1:1003518765466:ios:8b7539cae96df44b5e3223',
    messagingSenderId: '1003518765466',
    projectId: 'loginfirebase-aabf3',
    storageBucket: 'loginfirebase-aabf3.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebasep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZxFRN4f6iuS5xWVe_mK8fpdNuUw7j0Y',
    appId: '1:1003518765466:ios:8b7539cae96df44b5e3223',
    messagingSenderId: '1003518765466',
    projectId: 'loginfirebase-aabf3',
    storageBucket: 'loginfirebase-aabf3.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebasep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5RsYrFVX9oFdkPZo5f1z9TCLf4iD4yC0',
    appId: '1:1003518765466:web:96de2f55c42055295e3223',
    messagingSenderId: '1003518765466',
    projectId: 'loginfirebase-aabf3',
    authDomain: 'loginfirebase-aabf3.firebaseapp.com',
    storageBucket: 'loginfirebase-aabf3.firebasestorage.app',
    measurementId: 'G-4RB254TJYX',
  );
}
